import Head from "next/head"
import { db } from "../utils/firebase"
import { cloneElement, useEffect, useState } from "react"
import Message from "../components/Message"
import { collection, onSnapshot, orderBy, query } from "firebase/firestore"

export default function Home() {
  const [allPosts, setAllPosts] = useState([])

  const getPosts = async () => {
    const collectionRef = collection(db, "posts")
    const q = query(collectionRef, orderBy("timestamp", "desc"))
    const posts = await onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    })
    return posts
  }

  useEffect(() => {
    getPosts()
  }, [])

  return (
    <div>
      <Head>
        <title>Dev Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {allPosts.map((post) => (
          <Message {...post} key={post.id}></Message>
        ))}
      </div>
    </div>
  )
}
